/* ClassyC / MIR stdatomic.h — C11 atomics over MIR ALOAD/ASTORE/RMW/CAS.
   All ops are sequential consistency (order args to __atomic_* are ignored).
   See CLASSY-ATOMICS.md. */
static char stdatomic_str[]
  = "#ifndef __STDATOMIC_H\n"
    "#define __STDATOMIC_H\n"
    "\n"
    "#include <stddef.h>\n"
    "#undef __STDC_NO_ATOMICS__\n"
    "\n"
    "typedef enum {\n"
    "  memory_order_relaxed = 0,\n"
    "  memory_order_consume = 1,\n"
    "  memory_order_acquire = 2,\n"
    "  memory_order_release = 3,\n"
    "  memory_order_acq_rel = 4,\n"
    "  memory_order_seq_cst = 5\n"
    "} memory_order;\n"
    "\n"
    "typedef _Atomic _Bool atomic_bool;\n"
    "typedef _Atomic char atomic_char;\n"
    "typedef _Atomic signed char atomic_schar;\n"
    "typedef _Atomic unsigned char atomic_uchar;\n"
    "typedef _Atomic short atomic_short;\n"
    "typedef _Atomic unsigned short atomic_ushort;\n"
    "typedef _Atomic int atomic_int;\n"
    "typedef _Atomic unsigned int atomic_uint;\n"
    "typedef _Atomic long atomic_long;\n"
    "typedef _Atomic unsigned long atomic_ulong;\n"
    "typedef _Atomic long long atomic_llong;\n"
    "typedef _Atomic unsigned long long atomic_ullong;\n"
    "typedef _Atomic size_t atomic_size_t;\n"
    "typedef _Atomic ptrdiff_t atomic_ptrdiff_t;\n"
    "\n"
    "#define ATOMIC_VAR_INIT(value) (value)\n"
    "#define atomic_init(obj, value) atomic_store ((obj), (value))\n"
    "\n"
    "#define atomic_thread_fence(order) __atomic_thread_fence (order)\n"
    "#define atomic_signal_fence(order) __atomic_thread_fence (order)\n"
    "\n"
    "#define atomic_load(obj) __atomic_load_n ((obj), memory_order_seq_cst)\n"
    "#define atomic_load_explicit(obj, order) __atomic_load_n ((obj), (order))\n"
    "#define atomic_store(obj, des) __atomic_store_n ((obj), (des), memory_order_seq_cst)\n"
    "#define atomic_store_explicit(obj, des, order) \\\n"
    "  __atomic_store_n ((obj), (des), (order))\n"
    "#define atomic_exchange(obj, des) \\\n"
    "  __atomic_exchange_n ((obj), (des), memory_order_seq_cst)\n"
    "#define atomic_exchange_explicit(obj, des, order) \\\n"
    "  __atomic_exchange_n ((obj), (des), (order))\n"
    "\n"
    "#define atomic_fetch_add(obj, arg) \\\n"
    "  __atomic_fetch_add ((obj), (arg), memory_order_seq_cst)\n"
    "#define atomic_fetch_add_explicit(obj, arg, order) \\\n"
    "  __atomic_fetch_add ((obj), (arg), (order))\n"
    "#define atomic_fetch_sub(obj, arg) \\\n"
    "  __atomic_fetch_sub ((obj), (arg), memory_order_seq_cst)\n"
    "#define atomic_fetch_sub_explicit(obj, arg, order) \\\n"
    "  __atomic_fetch_sub ((obj), (arg), (order))\n"
    "#define atomic_fetch_and(obj, arg) \\\n"
    "  __atomic_fetch_and ((obj), (arg), memory_order_seq_cst)\n"
    "#define atomic_fetch_and_explicit(obj, arg, order) \\\n"
    "  __atomic_fetch_and ((obj), (arg), (order))\n"
    "#define atomic_fetch_or(obj, arg) \\\n"
    "  __atomic_fetch_or ((obj), (arg), memory_order_seq_cst)\n"
    "#define atomic_fetch_or_explicit(obj, arg, order) \\\n"
    "  __atomic_fetch_or ((obj), (arg), (order))\n"
    "#define atomic_fetch_xor(obj, arg) \\\n"
    "  __atomic_fetch_xor ((obj), (arg), memory_order_seq_cst)\n"
    "#define atomic_fetch_xor_explicit(obj, arg, order) \\\n"
    "  __atomic_fetch_xor ((obj), (arg), (order))\n"
    "\n"
    "#define atomic_compare_exchange_strong(obj, expected, desired) \\\n"
    "  __atomic_compare_exchange_n ((obj), (expected), (desired), 0, \\\n"
    "                               memory_order_seq_cst, memory_order_seq_cst)\n"
    "#define atomic_compare_exchange_strong_explicit(obj, expected, desired, s, f) \\\n"
    "  __atomic_compare_exchange_n ((obj), (expected), (desired), 0, (s), (f))\n"
    "#define atomic_compare_exchange_weak(obj, expected, desired) \\\n"
    "  atomic_compare_exchange_strong ((obj), (expected), (desired))\n"
    "#define atomic_compare_exchange_weak_explicit(obj, expected, desired, s, f) \\\n"
    "  atomic_compare_exchange_strong_explicit ((obj), (expected), (desired), (s), (f))\n"
    "\n"
    "#endif /* __STDATOMIC_H */\n";
